version: '3.5'
networks:
  productsapp:
    name: productsapp
    driver: bridge
services:
  nginx:
    container_name: productsapp_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/:/etc/nginx/conf.d/
      - ./docker/www_logs/nginx:/var/log/nginx
    links:
      - phpfpm
    networks:
      - productsapp
  phpfpm:
    ports:
      - "6665:6001"
    container_name: productsapp
    build: docker/containers/php-fpm
    command: bash -c "/etc/init.d/cron start && php-fpm -F"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - productsapp